- name: Install php-fpm & php extensions
  become: true
  apt: pkg={{ item }} state=present update_cache=true
  with_items:
  - php-fpm
  - php-gd
  - php-curl
  - php-mysql
  - php-dom
  - php-xml

- name: Configure php-fom with apache2
  become: true
  copy: src=files/www.conf dest=/etc/php/8.1/fpm/pool.d/

- name: Restart php-fpm
  become: yes
  service: name=php8.1-fpm state=restarted
