
- name: Add keys
  become: yes
  command: apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3B4FE6ACC0B21F32

- name: Add keys
  become: yes
  command: apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 40976EAF437D05B5

- name: Add the repository for MySql 5.6
  become: yes
  command: add-apt-repository universe -y

- name: Update
  become: yes
  command: apt-get update

- name: Install mysql
  apt: pkg={{ item }} state=present
  become: true
  with_items:    
    - mysql-server
    - mysql-client
    - python3-pip
    - python3-dev
    - python3-mysqldb
    - libmysqlclient-dev

- name : Ensure mysql started
  become: yes
  service: name=mysql state=started enabled=yes

- name: Update MySQL root password for all root accounts
  mysql_user: name=root 
              host={{ item }} 
              password={{ mysql_root_password }}
              login_user=root
              login_password=""
              state=present
  with_items:
    - 127.0.0.1
    - ::1
    - localhost